### ISSUE TITLE
Guide to setup private SolarNetwork service?

### ISSUE THREAD

**Issue by konstantinblaesi** [SolarNetwork/solarnetwork-central#1]
For those not familiar with OSGI it's not obvious how to build and run the service. Maybe provide a docker container?

**Comment by msqr** [comment]
Hi @konstantinblaesi,

I apologize for not noticing your comment until now. A Docker container for SolarNetwork would be convenient. I can imagine several different deployment scenarios however, including development focused, stand-alone all-in-one single server, and various split-apart container schemes. What is your interest in running SolarNetwork in a container, could you provide more details on what you're trying to do?

Have you seen the [SolarNetwork Vagrant VM](https://github.com/SolarNetwork/solarnetwork-dev/#vagrant-vm) (with more info [here](https://github.com/SolarNetwork/solarnetwork/wiki/Developer-VM))? That definitely makes it easy to get SolarNetwork running from a single-machine development point of view.

**Comment by konstantinblaesi** [comment]
My current setup consists of 4 SMA inverters wired up using RS485 to raspberry pi 3. I've used yasdishell from the yasdi sdk to test the connection. Do you know if I can use/extend this system to log and visualize the data of the photovoltaic plant? I saw that yasdi partially "integrated" here https://github.com/SolarNetwork/solarnetwork-external/tree/master/net.solarnetwork.yasdi4j but that code doesn't seem to do anything like pushing the data to a service or database.

**Comment by msqr** [comment]
You definitely can capture the data from your SMA inverters into SolarNetwork. The yasdi integration to collect the data is [in the SolarNode repository](https://github.com/SolarNetwork/solarnetwork-node/tree/master/net.solarnetwork.node.datum.sma.yasdi4j). Are you using the Raspberry Pi [SolarNode image](https://github.com/SolarNetwork/solarnetwork/wiki/Node-Prebuilt-Images)? That has yasdi, including `yasdishell`, integrated into the `solar` user's account. You can install the SolarNode yasdi plugin via the Plugins page in the SolarNode UI, as long as you first configure the [OBR Plugin Repository component](https://github.com/SolarNetwork/solarnetwork-node/tree/master/net.solarnetwork.node.setup.obr) that is also available in that Pi image.

**Comment by konstantinblaesi** [comment]
I've installed the SolarNode image on my Raspberry Pi and it seems to work (I only checked ssh and the webinterface). I'd prefer installing SolarNode via from a repository or docker image though. That sounds like it would be easier to maintain/update longterm.
Apart from that a guide how to deploy a SolarNetwork Central instance would be nice. I am currently trying to setup an eclipse dev env using https://github.com/SolarNetwork/solarnetwork/wiki/Eclipse-Setup-Guide but got stuck with this when trying to execute the run configuration *SolarNet*
```
!SESSION 2019-01-02 01:02:48.235 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -dev file:/home/konstantin/Projects/solarnetwork/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/SolarNetwork/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog -console

!ENTRY org.eclipse.osgi 4 0 2019-01-02 01:02:48.531
!MESSAGE Startup error
!STACK 1
java.lang.RuntimeException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.resume(InternalSystemBundle.java:233)
	at org.eclipse.osgi.framework.internal.core.Framework.launch(Framework.java:656)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:275)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:734)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.resume(InternalSystemBundle.java:225)
	... 11 more
Caused by: java.lang.IllegalStateException: The System Bundle could not be resolved: Missing Constraint: Bundle-RequiredExecutionEnvironment: J2SE-1.5
	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.checkSystemState(BaseStorage.java:827)
	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.getStateManager(BaseStorage.java:800)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.getState(BaseAdaptor.java:387)
	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.frameworkStart(BaseStorage.java:923)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.frameworkStart(BaseAdaptor.java:250)
	at org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start(SystemBundleActivator.java:60)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	... 13 more
An error has occurred. See the log file
/home/konstantin/Projects/solarnetwork/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/SolarNetwork/1546387368352.log.
```
I also see this warning when trying to launch https://imgur.com/a/p1rdPUP. Do I need to use an older jdk/jre?
I use Fedora 29, but installed the latest Eclipse 4.10 from their website. My main interest right now is
* logging the data from the SMA inverters using SolarNet
* exploring the visualization options SolarNet offers

**Comment by konstantinblaesi** [comment]
Ok it was late yesterday and apparently I forgot to set Run confifigurations > SolarNet > Arguments > Working directory > Other to ` ${workspace_loc:solarnetwork-osgi-target}` . Looks much better now!

**Comment by konstantinblaesi** [comment]
Why is database setup a manual step? I've seen other frameworks where all that's needed is the connection details and the app does the migrations on it's own. Also this plv8 thing - never heard of it - is it very important? I can't find anything about in fedora, except that it's maintainer seems to have given up on it? :(

**Comment by msqr** [comment]
> I've installed the SolarNode image on my Raspberry Pi and it seems to work (I only checked ssh and the webinterface). I'd prefer installing SolarNode via from a repository or docker image though. That sounds like it would be easier to maintain/update longterm.

We would like to have SolarNode [available as a Debian package](https://data.solarnetwork.net/jira/browse/NODE-132) as well. Distributing the OS images is currently the easiest way for people to deploy to devices, but hopefully at some point someone will have availability to tackle packaging options. Docker isn't really a target we have for SolarNode.

**Comment by msqr** [comment]
> Why is database setup a manual step? I've seen other frameworks where all that's needed is the connection details and the app does the migrations on it's own. Also this plv8 thing - never heard of it - is it very important? I can't find anything about in fedora, except that it's maintainer seems to have given up on it? :(

The database is manually managed because we configure the database quite differently in production environments and the plv8 setup (which is integral to the application) requires integration with the Postgres server configuration. That being said, I'm sure with some dedicated effort a more automated solution could be incorporated... pull requests are welcome.

We have not tried running SolarNet on Fedora. Our primary infrastructure is FreeBSD based. The Vagrant VM uses Ubuntu. Both support plv8 out of the box.

**Comment by msqr** [comment]
> Ok it was late yesterday and apparently I forgot to set Run confifigurations > SolarNet > Arguments > Working directory > Other to ` ${workspace_loc:solarnetwork-osgi-target}` . Looks much better now!

Glad you got it working in the end. Sorry for the delayed responses, I have been away on holiday.

**Comment by msqr** [comment]
I shall close this issue now, feel free to re-open or post other questions as needed.
